'use client';

import { use, useState, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { 
  ChevronLeft, 
  Download, 
  Calendar as CalendarIcon, 
  AlertCircle, 
  CheckCircle2, 
  FileText,
  Clock,
  Filter
} from 'lucide-react';
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { mockPatients, mockEncounters } from '@/lib/mock-data';
import { format, isAfter, subDays } from 'date-fns';
import { useRouter } from 'next/navigation';
import { usePrint } from '@/hooks/usePrint';
import { cn } from '@/lib/utils';

export default function PatientHistoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const { print } = usePrint();
  const [timeFilter, setTimeFilter] = useState('all');

  const patient = mockPatients.find(p => p.id === id);
  const encounters = mockEncounters.filter(e => e.patientId === id);

  const filteredEncounters = useMemo(() => {
    if (timeFilter === 'all') return encounters;
    const now = new Date();
    const days = parseInt(timeFilter);
    const cutoff = subDays(now, days);
    return encounters.filter(e => isAfter(new Date(e.date), cutoff));
  }, [encounters, timeFilter]);

  const handleDownload = () => {
    if (!patient) return;

    const reportContent = (
      <div className="p-8 font-sans max-w-4xl mx-auto bg-white text-slate-900">
        <header className="border-b-2 border-primary pb-6 mb-8 flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold text-primary">Clinical History Report</h1>
            <p className="text-sm text-slate-500 mt-1">AI Epilepsy Assistant • Confidential Patient Record</p>
          </div>
          <div className="text-right">
            <p className="font-bold">{format(new Date(), 'PPP')}</p>
            <p className="text-xs text-slate-400">Generated by {patient.village} Sector</p>
          </div>
        </header>

        <section className="grid grid-cols-2 gap-6 mb-10 bg-slate-50 p-6 rounded-xl border border-slate-200">
          <div>
            <h2 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-2">Patient Demographics</h2>
            <div className="space-y-1">
              <p className="text-lg font-bold">{patient.name}</p>
              <p className="text-sm">Age: {patient.age}Y • {patient.gender}</p>
              <p className="text-sm">{patient.village}</p>
              <p className="text-sm">{patient.contact}</p>
            </div>
          </div>
          <div className="text-right">
            <h2 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-2">Report Summary</h2>
            <p className="text-sm">Total Encounters: {filteredEncounters.length}</p>
            <p className="text-sm">Filter: {timeFilter === 'all' ? 'Full History' : `Last ${timeFilter} Days`}</p>
            <Badge className="mt-2" variant={patient.status === 'Urgent' ? 'destructive' : 'secondary'}>
              Status: {patient.status}
            </Badge>
          </div>
        </section>

        <section className="space-y-8">
          <h2 className="text-xl font-bold border-b pb-2">Encounter Timeline</h2>
          {filteredEncounters.length > 0 ? (
            filteredEncounters.map((e, i) => (
              <div key={e.id} className="relative pl-8 border-l-2 border-slate-100">
                <div className="absolute -left-[9px] top-0 h-4 w-4 rounded-full bg-primary border-4 border-white shadow-sm" />
                <div className="mb-1 flex items-center justify-between">
                  <span className="text-sm font-bold text-slate-500 uppercase tracking-tighter">
                    {format(new Date(e.date), 'PPP p')}
                  </span>
                  <Badge variant="outline" className="text-[10px] uppercase font-bold">{e.type}</Badge>
                </div>
                <div className="space-y-4">
                  <div>
                    <h4 className="text-[10px] font-bold uppercase text-slate-400">Clinical Summary</h4>
                    <p className="text-sm leading-relaxed">{e.summary}</p>
                  </div>
                  {e.redFlags.length > 0 && (
                    <div>
                      <h4 className="text-[10px] font-bold uppercase text-red-600">Red Flags Detected</h4>
                      <ul className="list-disc pl-4 mt-1">
                        {e.redFlags.map((flag, idx) => (
                          <li key={idx} className="text-xs font-medium text-red-900">{flag}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  <div className="bg-primary/5 p-3 rounded-lg border border-primary/10">
                    <h4 className="text-[10px] font-bold uppercase text-primary mb-1">Recommended Action</h4>
                    <p className="text-sm font-medium text-slate-800">{e.recommendation}</p>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <p className="text-center py-10 text-slate-400 italic">No records found for the selected period.</p>
          )}
        </section>

        <footer className="mt-20 pt-6 border-t text-center text-[10px] text-slate-400">
          <p>This report is generated for authorized healthcare workers only. Handle with extreme confidentiality.</p>
          <p className="mt-1">© 2024 AI Epilepsy Assistant | Powered by WHO Clinical Protocols</p>
        </footer>
      </div>
    );

    print(reportContent);
  };

  if (!patient) return <div className="p-10 text-center">Patient not found</div>;

  return (
    <div className="space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <Button variant="ghost" size="sm" onClick={() => router.back()} className="-ml-2 text-muted-foreground">
          <ChevronLeft className="h-4 w-4 mr-1" /> Records
        </Button>
        <Button onClick={handleDownload} variant="outline" size="sm" className="gap-2 border-primary text-primary hover:bg-primary/5">
          <Download className="h-4 w-4" /> Download PDF
        </Button>
      </div>

      <div className="flex flex-col gap-1">
        <h1 className="text-2xl font-headline font-bold text-primary">{patient.name}</h1>
        <p className="text-sm text-muted-foreground">Clinical History & Encounter Log</p>
      </div>

      <div className="flex items-center gap-3 bg-card p-3 rounded-xl border border-muted shadow-sm">
        <Filter className="h-4 w-4 text-muted-foreground shrink-0" />
        <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Filter Period</span>
        <Select value={timeFilter} onValueChange={setTimeFilter}>
          <SelectTrigger className="h-9 border-none bg-transparent focus:ring-0 text-sm font-bold">
            <SelectValue placeholder="Select period" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Full History</SelectItem>
            <SelectItem value="7">Last 7 Days</SelectItem>
            <SelectItem value="30">Last 30 Days</SelectItem>
            <SelectItem value="90">Last 90 Days</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-6">
        {filteredEncounters.length > 0 ? (
          filteredEncounters.map((encounter) => (
            <Card key={encounter.id} className="border-none shadow-md overflow-hidden bg-card/50">
              <CardHeader className="p-4 bg-muted/20 border-b">
                <div className="flex justify-between items-start">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2 text-primary font-bold">
                      <Clock className="h-4 w-4" />
                      <span className="text-sm">{format(new Date(encounter.date), 'PPP p')}</span>
                    </div>
                    <Badge variant="secondary" className="h-5 text-[9px] uppercase tracking-wider">{encounter.type}</Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4 space-y-4">
                <section>
                  <div className="flex items-center gap-2 mb-1 text-muted-foreground">
                    <FileText className="h-3 w-3" />
                    <h4 className="text-[10px] font-bold uppercase tracking-widest">Clinical Summary</h4>
                  </div>
                  <p className="text-sm leading-relaxed text-foreground/90">{encounter.summary}</p>
                </section>

                {encounter.redFlags.length > 0 && (
                  <section className="bg-red-50/50 p-3 rounded-lg border border-red-100">
                    <div className="flex items-center gap-2 mb-2 text-red-600">
                      <AlertCircle className="h-3 w-3" />
                      <h4 className="text-[10px] font-bold uppercase tracking-widest">Red Flags Detected</h4>
                    </div>
                    <ul className="space-y-1">
                      {encounter.redFlags.map((flag, idx) => (
                        <li key={idx} className="text-xs font-medium text-red-950 flex items-center gap-2">
                          <div className="h-1 w-1 rounded-full bg-red-400" /> {flag}
                        </li>
                      ))}
                    </ul>
                  </section>
                )}

                <section className="bg-primary/5 p-3 rounded-lg border border-primary/10">
                  <div className="flex items-center gap-2 mb-1 text-primary">
                    <CheckCircle2 className="h-3 w-3" />
                    <h4 className="text-[10px] font-bold uppercase tracking-widest">Recommended Action</h4>
                  </div>
                  <p className="text-sm font-bold text-slate-800">{encounter.recommendation}</p>
                </section>
              </CardContent>
            </Card>
          ))
        ) : (
          <div className="text-center py-20 bg-muted/10 rounded-2xl border-2 border-dashed">
            <CalendarIcon className="h-10 w-10 text-muted-foreground/30 mx-auto mb-2" />
            <p className="text-sm text-muted-foreground font-medium">No encounters found for this period.</p>
          </div>
        )}
      </div>
    </div>
  );
}
